---
language: python
services:
  - docker

install:
  - pip install molecule['docker'] docker-py

before_script:
  - cd ../
  - mv ansible-role-nginx rchouinard.nginx
  - cd rchouinard.nginx/

script:
  - molecule --debug test
