---
- name: Install packages
  become: yes
  dnf:
    name: "{{ nginx_packages }}"
    state: present

- name: Enable service
  become: yes
  service:
    name: nginx
    enabled: yes
    state: started

- name: Create vhost config directory
  become: yes
  file:
    path: "/etc/nginx/sites.d"
    state: directory

- name: Install configuration
  become: yes
  copy:
    src: "{{ item }}"
    dest: "/etc/nginx/{{ item }}"
  with_items:
    - nginx.conf
    - mime.types
    - fastcgi_params
  notify: restart nginx
