---
- name: Install package
  package:
    name: "{{ nginx_package }}"
    state: present

- name: Install extra packages
  package:
    name: "{{ nginx_extra_packages | list }}"
    state: present
  when: nginx_extra_packages | list

- name: Create server config directory
  file:
    path: /etc/nginx/server.d
    mode: 0755
    seuser: system_u
    serole: object_r
    setype: httpd_config_t
    state: directory

- name: Install H5BP configuration
  copy:
    src: "{{ item }}"
    dest: /etc/nginx/
    mode: 0644
    seuser: system_u
    serole: object_r
    setype: httpd_config_t
  loop:
    - h5bp
    - mime.types
  notify: restart nginx

- name: Install main configuration
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: 0644
    seuser: system_u
    serole: object_r
    setype: httpd_config_t
  notify: restart nginx

- name: Enable service
  service:
    name: nginx
    enabled: yes
    state: started
