---
- name: Install packages
  package:
    name: "{{ nginx_packages }}"
    state: present

- name: Enable service
  service:
    name: nginx
    enabled: yes
    state: started

- name: Create vhost config directory
  file:
    path: "/etc/nginx/sites.d"
    mode: 0755
    seuser: system_u
    serole: object_r
    setype: httpd_config_t
    state: directory

- name: Install main configuration
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: 0644
    seuser: system_u
    serole: object_r
    setype: httpd_config_t
  notify: restart nginx

- name: Install additional configuration
  copy:
    src: mime.types
    dest: /etc/nginx/mime.types
    mode: 0644
    seuser: system_u
    serole: object_r
    setype: httpd_config_t
  notify: restart nginx

- name: Configure upstreams
  template:
    src: upstream.conf.j2
    dest: "/etc/nginx/conf.d/{{ upstream.name }}.conf"
    mode: 0644
    seuser: system_u
    serole: object_r
    setype: httpd_config_t
  loop: "{{ nginx_upstreams }}"
  loop_control:
    loop_var: upstream
    label: "{{ upstream.name }}"
  when: nginx_upstreams is not empty
  notify: restart nginx
