---
- name: restart nginx
  become: yes
  service:
    name: nginx
    state: restarted

- name: reload nginx
  become: yes
  service:
    name: nginx
    state: reloaded

- name: enable nginx
  become: yes
  service:
    name: nginx
    enabled: yes
    state: started
