# Molecule managed

{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

# Fedora 30's Python transition is less than smooth
RUN if [ $(command -v dnf) ]; then \
        if [ $(grep VERSION_ID /etc/os-release | cut -d= -f2) == '30' ]; then \
            dnf makecache && dnf -y install python3 sudo python3-devel python3-dnf bash && dnf clean all; \
        else \
            dnf makecache && dnf -y install python sudo python-devel python*-dnf bash && dnf clean all; \
        fi \
    elif [ $(command -v yum) ]; then \
        yum makecache fast && yum install -y python sudo yum-plugin-ovl bash && sed -i 's/plugins=0/plugins=1/g' /etc/yum.conf && yum clean all; \
    fi
