---
systemd_template: &systemd
  command: /sbin/init
  environment:
    container: docker
  tmpfs:
    - /run
    - /tmp
  volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup:ro
  privileged: true

dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: fedora-34
    image: geerlingguy/docker-fedora34-ansible:latest
    <<: *systemd
  - name: fedora-33
    image: geerlingguy/docker-fedora33-ansible:latest
    <<: *systemd
  - name: centos-8
    image: geerlingguy/docker-centos8-ansible:latest
    <<: *systemd
  - name: centos-7
    image: geerlingguy/docker-centos7-ansible:latest
    <<: *systemd
provisioner:
  name: ansible
verifier:
  name: ansible
