---
- name: Prepare
  hosts: all
  tasks:

    - name: install nginx repository configuration
      copy:
        dest: /etc/yum.repos.d/nginx.repo
        content: |
          [nginx]
          name=nginx repo
          baseurl=http://nginx.org/packages/centos/$releasever/$basearch/
          gpgcheck=0
          enabled=1
      when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"
