---
- name: Prepare
  hosts: all
  tasks:

  - name: Enable EPEL for CentOS 7
    yum:
      name: epel-release
      state: present
    when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"
